version: "3"
services:
  go:
    image: golang:1.13
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     GOLANG_VERSION: 1.13
    volumes:
      - $PWD:/go/src/github.com/mactynow/trigger
    stdin_open: true
    tty: true
